version: '3.5'

services:
  wso2am:
    build:
      context: ./wso2am
    volumes:
      - ./wso2am/deployment.toml:/home/wso2carbon/wso2am-3.2.0/repository/conf/deployment.toml
    ports:
      - "8280:8280"
      - "8243:8243"
      - "9443:9443"